id: c5a6f577f5b24b9e9a723ddead06050a
initial_creation_type: ocr
source_metadata:
  volumes:
    0ee4d562c5cf423bb1e215781fae2d54:
      base_file: v066.txt
      image_group_id: I1PD95912
      title: འཕགས་པ་བཟང་པོ་སྤྱོད་པའི་སྨོན་ལམ་གྱི་རྒྱལ་པོ་ཆེན་པོའི་བཤད་སྦྱར།
      total_pages: 1529
      volume_number: 67
